services:
  # Frontend React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  # Backend PHP
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    environment:
      - DB_DRIVER=sqlite
      - DB_DATABASE=/var/www/html/database/events.sqlite

  # Test service for E2E testing
  tests:
    image: mcr.microsoft.com/playwright:v1.40.0-focal
    working_dir: /app
    volumes:
      - ./tests:/app
      - ./tests/node_modules:/app/node_modules
    environment:
      - CI=true
      - PLAYWRIGHT_BASE_URL=http://frontend:5173
    command: sh -c "npm install && npx playwright install && npm run test"
    depends_on:
      - frontend
      - backend
    profiles:
      - test
